name: logs_mobile_app
description: Logs mobile app frontend for personal logging and journaling.

publish_to: 'none' # Private project

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^5.9.0
  
  # Local storage
  shared_preferences: ^2.5.3

  # JSON serialization runtime annotations
  json_annotation: ^4.8.0

  # Navigation
  go_router: ^16.2.2

  # AWS Amplify (updated to latest stable)
  amplify_flutter: ^2.6.5
  flutter_native_splash: ^2.4.6
  riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.3.1
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation tools
  build_runner: ^2.4.4
  json_serializable: ^6.5.4

  # Optional: Linting
  flutter_lints: ^6.0.0
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_bw.png"
  min_sdk_android: 21 

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/icon.png